AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resume Skills Scorer - Lambda + Bedrock (SAM)

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 512
    Architectures:
      - arm64
    Tracing: Active

Parameters:
  BedrockRegion:
    Type: String
    Default: us-east-1
    Description: Bedrock region used by the tool
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-5-sonnet-20240620-v1:0
    Description: Bedrock model identifier
  FunctionName:
    Type: String
    Default: jd-resume-skills-scorer
    Description: Lambda function name

Resources:
  ResumeSkillsScorerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: .
      Handler: handler.handler
      Environment:
        Variables:
          BEDROCK_REGION: !Ref BedrockRegion
          BEDROCK_MODEL_ID: !Ref BedrockModelId
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: '*'

Outputs:
  FunctionArn:
    Description: Deployed Lambda ARN
    Value: !GetAtt ResumeSkillsScorerFunction.Arn


